config/routes.rb
Rails.application.routes.draw do
  get 'campingtripplanningtools/list' => 'campingtripplanningtools#list'
  resources :campingtripplanningtools

  resources :events

  resources :posts

  devise_for :users
  get 'welcome/index'

  get 'pages/about'

  get 'pages/contact'

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/campingtripplanningtool.rb
class Campingtripplanningtool < ActiveRecord::Base
	geocoded_by :city
	after_validation :geocode
end

app/controllers/campingtripplanningtools_controller.rb
class CampingtripplanningtoolsController < ApplicationController
  before_action :set_campingtripplanningtool, only: [:show, :edit, :update, :destroy]

  # GET /campingtripplanningtools
  # GET /campingtripplanningtools.json
  def index
    @campingtripplanningtools = Campingtripplanningtool.all
    @meanmarker = 1
    @meanlat = 0;
    @meanlong = 0;
    @count = 0;
    @campingtripplanningtools.each do |user|
      @meanlat += user.latitude
      @meanlong+= user.longitude
      @count += 1
    end
    @meanlat = @meanlat / @count
    @meanlong = @meanlong / @count
    @hash = Gmaps4rails.build_markers(@campingtripplanningtools) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.title (user.fname + " " + user.lname)
    end
    @hash2 = Gmaps4rails.build_markers(@meanmarker) do |user, marker|
      marker.lat @meanlat
      marker.lng @meanlong
      marker.title "Central Location"
    end
  end

  def list
    @campingtripplanningtools = Campingtripplanningtool.all
  end

  # GET /campingtripplanningtools/1
  # GET /campingtripplanningtools/1.json
  def show
  end

  # GET /campingtripplanningtools/new
  def new
    @campingtripplanningtool = Campingtripplanningtool.new
  end

  # GET /campingtripplanningtools/1/edit
  def edit
  end

  # POST /campingtripplanningtools
  # POST /campingtripplanningtools.json
  def create
    @campingtripplanningtool = Campingtripplanningtool.new(campingtripplanningtool_params)

    respond_to do |format|
      if @campingtripplanningtool.save
        format.html { redirect_to @campingtripplanningtool, notice: 'Campingtripplanningtool was successfully created.' }
        format.json { render :show, status: :created, location: @campingtripplanningtool }
      else
        format.html { render :new }
        format.json { render json: @campingtripplanningtool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campingtripplanningtools/1
  # PATCH/PUT /campingtripplanningtools/1.json
  def update
    respond_to do |format|
      if @campingtripplanningtool.update(campingtripplanningtool_params)
        format.html { redirect_to @campingtripplanningtool, notice: 'Campingtripplanningtool was successfully updated.' }
        format.json { render :show, status: :ok, location: @campingtripplanningtool }
      else
        format.html { render :edit }
        format.json { render json: @campingtripplanningtool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campingtripplanningtools/1
  # DELETE /campingtripplanningtools/1.json
  def destroy
    @campingtripplanningtool.destroy
    respond_to do |format|
      format.html { redirect_to campingtripplanningtools_url, notice: 'Campingtripplanningtool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campingtripplanningtool
      @campingtripplanningtool = Campingtripplanningtool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campingtripplanningtool_params
      params.require(:campingtripplanningtool).permit(:fname, :lname, :city, :state, :latitude, :longitude, :gmaps)
    end
end

app/helpers/campingtripplanningtools_helper.rb
module CampingtripplanningtoolsHelper
end

app/views/campingtripplanningtools/_form.html.erb
<%= form_for(@campingtripplanningtool) do |f| %>
  <% if @campingtripplanningtool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campingtripplanningtool.errors.count, "error") %> prohibited this campingtripplanningtool from being saved:</h2>

      <ul>
      <% @campingtripplanningtool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>First Name<h4>
    <%= f.text_field :fname, class: "form-control" %>
  </div>
  <div class="field">
    <h4>Last Name</h4>
    <%= f.text_field :lname, class: "form-control" %>
  </div>
  <div class="field">
    <h4>City, State</h4>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Insert Information", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/campingtripplanningtools/edit.html.erb
<h1>Editing campingtripplanningtool</h1>

<%= render 'form' %>

<%= link_to 'Show', @campingtripplanningtool %> |
<%= link_to 'Back', campingtripplanningtools_path %>

app/views/campingtripplanningtools/index.html.erb
<div>
  <%= link_to 'Add Your Name', new_campingtripplanningtool_path %> | <%= link_to 'List View', campingtripplanningtools_list_path %>
</div>
<div class="jumbotron" id="map-container">
</div>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map-container'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  meanmarker = handler.addMarkers(<%=raw @hash2.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/campingtripplanningtools/list.html.erb
<h1>Attendance</h1>
<p>At this point this page will just show who is planning on attending the camping trip.  In the future I plan on adding a map to show where each person is as well as the exact center of each of us as sort of a suggestion as to where we should have the camping trip.</p>
<p>I was also thinking about adding a section to show what people can bring.  If you think that would be a good idea or if you have any other suggestions, please add a comment to the 3/1 81's post I submit about this tool and I will see about adding it to the page.</p>

<hr>

<table style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campingtripplanningtools.each do |campingtripplanningtool| %>
      <tr>
        <td><%= campingtripplanningtool.fname + " " + campingtripplanningtool.lname %></td>
        <td><%= campingtripplanningtool.city %></td>
        <% if user_signed_in? && current_user.email == 'bheller2010@live.com' %>
          <td><%= button_to 'Destroy', campingtripplanningtool, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Name', new_campingtripplanningtool_path, class: "btn btn-primary" %>

app/views/campingtripplanningtools/new.html.erb
<h1>New campingtripplanningtool</h1>

<%= render 'form' %>

<%= link_to 'Back', campingtripplanningtools_path %>

app/views/campingtripplanningtools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @campingtripplanningtool.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @campingtripplanningtool.lname %>
</p>

<p>
  <strong>City:</strong>
  <%= @campingtripplanningtool.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @campingtripplanningtool.state %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @campingtripplanningtool.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @campingtripplanningtool.longitude %>
</p>

<p>
  <strong>Gmaps:</strong>
  <%= @campingtripplanningtool.gmaps %>
</p>

<%= link_to 'Edit', edit_campingtripplanningtool_path(@campingtripplanningtool) %> |
<%= link_to 'Back', campingtripplanningtools_path %>