config/routes.rb
Rails.application.routes.draw do
  get 'campingtripplanningtools/list' => 'campingtripplanningtools#list'
  resources :campingtripplanningtools

  resources :events

  resources :posts

  devise_for :users
  get 'welcome/index'

  get 'pages/about'

  get 'pages/contact'

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<center>&copy 2014 addgamerz.com<br/></center>
	</small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
 		<div class="container">
    		<div class="navbar-header">
      			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        			<span class="sr-only">Toggle navigation</span>
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
        		</button>
        		<%= link_to 'ADDGamerz', root_path, class: "navbar-brand" %>
      		</div>
    		<div class="navbar-collapse collapse">
      			<ul class="nav navbar-nav">
      				<% if current_page?(root_path) %>
      					<li class="active"><%= link_to 'Home', root_path %></li>
      				<% else %>
      					<li><%= link_to 'Home', root_path %></li>
      				<% end %>

      				<% if current_page?(pages_about_path) %>
      					<li class="active"><%= link_to 'About', pages_about_path %></li>
      				<% else %>
      					<li><%= link_to 'About', pages_about_path %></li>
      				<% end %>

      				<% if current_page?(pages_contact_path) %>
      					<li class="active"><%= link_to 'Contact', pages_contact_path %></li>
      				<% else %>
      					<li><%= link_to 'Contact', pages_contact_path %>
      				<% end %>
        		</ul>
<!--             <p class="navbar-text pull-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to('Logout', destroy_user_session_path) %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </p> -->
    		</div><!--/.nav-collapse -->
  		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ADDGamerz || Owning noobs since... Forever...</title>
  <%= favicon_link_tag 'icon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'rails.js' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <%= javascript_include_tag 'jquery-1.11.1.min.js' %>
</body>
</html>